### ISSUE TITLE
Crashes when used with Atlas Combat

### ISSUE THREAD

**Issue by MonstoBusta** [fxmorin/memoryLeakFix#69]
The crash does not occur on startup, but it occurs as soon as the game has to render anything (joining a world or a server). I know it has to do with memory leak fix as I can play fine if I remove either Atlas Combat or Memory Leak Fix.

A relevant log
[crash-2023-01-30_20.47.39-client.txt](https://github.com/fxmorin/MemoryLeakFix/files/10552525/crash-2023-01-30_20.47.39-client.txt)

**Comment by FxMorin** [comment]
Please also make an issue on the atlas combat github. There mod should not be breaking the networking code like that

**Comment by MonstoBusta** [comment]
I have reported the issue to the Atlas devs first, and they do not see the issue on their part.
In addition, I believe that Atlas breaking vanilla networking code is intentional, as the features it's trying to replicate are not things possible in vanilla outside of the combat test snapshots.

**Comment by Alexandra-Myers** [comment]
> Please also make an issue on the atlas combat github. There mod should not be breaking the networking code like that

As a developer who examined this issue, this seems to be due to the fact that you are trying to cast the packets to ExtendPacketByteBuf without first checking if it can. On my end, I cannot implement ExtendPacketByteBuf in my own custom packet because it does not exist. and all it does is add another packet. I am not breaking vanilla networking code, this is merely a case where you never anticipated a mod to do this, so you never had a contingency plan for if it does not implement ExtendPacketByteBuf. I recommend adding a check to see if it implements it first, or perhaps you can suggest a way for me to implement it without requiring MemoryLeakFix for the end user?

**Comment by FxMorin** [comment]
@Alexandra-Myers Does fabric API not provide a way for mods to extend packets?
I'll be looking into this soon

**Comment by Alexandra-Myers** [comment]
it does not.

**Comment by Alexandra-Myers** [comment]
Of course it is possible it does and this is a mistake on my end, but still.

**Comment by FxMorin** [comment]
It will be fixed in the next release
