### ISSUE TITLE
Charm's Mixin should be final

### ISSUE THREAD

**Issue by MissPotato** [fxmorin/memoryLeakFix#74]
After the mixin reload log says that Charm's mixin should be final. Followed by an error.  

MemoeryLeakFix: 0.7.0
Fabric Loader: 0.14.17
Fabric API 0.75-1
Minecraft: 1.19.2
Enviroment: Dedicated server, Ubuntu OS - VPS
latest.log: https://mclo.gs/XkxP88F#L1701

**Comment by FxMorin** [comment]
That issue is Charm's fault. MemoryLeakFix loads all mods before the game starts instead of when they are needed. This means that charm has this issue but I just show it on load.
However that second issue is an actual problem. Might be due to another mod removing `NO_GROUP` (probably not) or Mixin has updated and changed the name or location of that variable.
I'll look into it, same as #73

**Comment by FxMorin** [comment]
After further analysis, this crash not even remotely close to MemoryLeakFix. It's caused by some other mod.
When `NO_GROUP` is not found by MemoryLeakFix, it does not crash. It simply prints the error to logs and continues running

**Comment by MissPotato** [comment]
Ah, sorry for wasting your time! I assumed it was MLF because it happened at the force reload. Thank you for looking into it! 

For other people coming to report the same issue: the error can reproduced with just MLF, Charm, and Fabric API. I have reported it to the Charm
